export const actionTypes = {
	DETAILS_START: "DETAILS_START",
	DETAILS_SUCCESS: "DETAILS_SUCCESS",
	DETAILS_FAILURE: "DETAILS_FAILURE",

	TOKEN_START: "TOKEN_START",
	TOKEN_SUCCESS: "TOKEN_SUCCESS",
	TOKEN_FAILURE: "TOKEN_FAILURE",

	RESET: "RESET",
}
